[package]
name = "gigabytectl"
version = "0.6.1"
edition = "2024"
description = "A simple Rust-based TUI tool for controlling laptops using the gigabyte-laptop-wmi kernel module."
license = "MIT"
repository = "https://github.com/Code-Sapling/gigabytectl"
readme = "README.md"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5", features = ["derive"] }
clap_complete = "4.5"
crossterm = "0.29.0"
ratatui = "0.30.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

[profile.release]
lto = true
codegen-units = 1
strip = true
